name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        TAG="superclient.jfrog.io/artifactory/docker-trial/python_app:1"
        docker build . --file Dockerfile --tag $TAG
        echo "${{ secrets.JF_PASSWORD }}" | docker login https://superclient.jfrog.io/artifactory/docker-trial/ --username johntest --password-stdin
        docker push $TAG

        
      
